# Generated by Django 3.2.9 on 2021-11-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211119_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_ru',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_uz',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='banner_en',
            field=models.ImageField(null=True, upload_to='post banners', verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='banner_ru',
            field=models.ImageField(null=True, upload_to='post banners', verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='banner_uz',
            field=models.ImageField(null=True, upload_to='post banners', verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_en',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title_uz',
            field=models.CharField(max_length=512, null=True, verbose_name='title'),
        ),
    ]
