# Generated by Django 3.2.9 on 2021-11-20 08:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20211119_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourtagmodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourtagmodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tourtagmodel',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
